#!/usr/bin/env node

import 'dotenv/config'
import { writeFileSync, existsSync, mkdirSync } from 'fs'
import { execSync } from 'child_process'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'
import inquirer from 'inquirer'
import chalk from 'chalk'

const __dirname = dirname(fileURLToPath(import.meta.url))
const projectRoot = dirname(__dirname)
const envFile = join(projectRoot, '.env')

function isValidBotToken(token) {
  return /^\d+:[A-Za-z0-9_-]+$/.test(token)
}

function isValidChatId(id) {
  return /^-?\d+$/.test(id)
}

function isValidDomain(domain) {
  return /^([a-z0-9]([a-z0-9-]*[a-z0-9])?\.)*[a-z0-9]([a-z0-9-]*[a-z0-9])?$/.test(domain)
}

function isValidIp(ip) {
  const parts = ip.split('.')
  return parts.length === 4 && parts.every(p => {
    const num = parseInt(p)
    return num >= 0 && num <= 255
  })
}

function detectIpAddress() {
  try {
    const result = execSync("hostname -I 2>/dev/null | awk '{print $1}' || curl -sf ifconfig.me 2>/dev/null || echo ''", { stdio: ['pipe', 'pipe', 'pipe'] })
    const ip = result.toString().trim()
    if (ip && isValidIp(ip)) return ip
  } catch {}
  return null
}

function detectClaudeCode(providedPath) {
  if (providedPath && existsSync(providedPath)) {
    return providedPath
  }

  try {
    const which = execSync('which claude 2>/dev/null', { stdio: ['pipe', 'pipe', 'pipe'] })
    const p = which.toString().trim()
    if (p) return p
  } catch {}

  const paths = [
    process.env.CLAUDE_CLI,
    '/usr/local/bin/claude',
    '/usr/local/bin/claude-code',
  ]

  for (const path of paths) {
    if (path && existsSync(path)) return path
  }

  return null
}

async function runSetupWizard() {
  console.log(chalk.cyan(`\n┌─────────────────────────────────────────────────────┐`))
  console.log(chalk.cyan(`│  VPS-CODE-BOT Setup                                  │`))
  console.log(chalk.cyan(`│  Configure your intelligent VPS platform             │`))
  console.log(chalk.cyan(`└─────────────────────────────────────────────────────┘\n`))

  // Check if already configured
  if (existsSync(envFile) && process.env.BOT_TOKEN && process.env.CHAT_ID) {
    const { reconfigure } = await inquirer.prompt([
      {
        type: 'confirm',
        name: 'reconfigure',
        message: 'System already configured. Reconfigure?',
        default: false,
      },
    ])

    if (!reconfigure) {
      console.log(chalk.gray('\nSetup skipped.\n'))
      return
    }
  }

  // Detect Claude Code CLI
  const cliArg = process.argv.includes('--claude-cli')
    ? process.argv[process.argv.indexOf('--claude-cli') + 1]
    : null
  let cliPath = (cliArg && cliArg !== '' && cliArg !== '--os') ? cliArg : detectClaudeCode()

  if (cliPath) {
    console.log(chalk.green(`✓ Claude Code CLI: ${cliPath}\n`))
  } else {
    cliPath = 'claude'
    console.log(chalk.yellow('⚠ Claude Code CLI not found — will use "claude" from PATH\n'))
  }

  // Auto-detect IP
  const ipAddress = detectIpAddress() || 'localhost'
  console.log(chalk.green(`✓ Server IP: ${ipAddress}\n`))

  // Prompt for all required settings
  const answers = await inquirer.prompt([
    {
      type: 'input',
      name: 'botToken',
      message: 'Telegram Bot Token (from @BotFather):',
      default: process.env.BOT_TOKEN || '',
      validate: (input) => {
        if (!input) return 'Required'
        if (!isValidBotToken(input)) return 'Invalid format — should be 123456:ABC-...'
        return true
      },
    },
    {
      type: 'input',
      name: 'chatId',
      message: 'Your Telegram Chat ID (from @userinfobot):',
      default: process.env.CHAT_ID || '',
      validate: (input) => {
        if (!input) return 'Required'
        if (!isValidChatId(input)) return 'Must be a number'
        return true
      },
    },
    {
      type: 'input',
      name: 'domain',
      message: `Domain (leave blank to use IP ${ipAddress}):`,
      default: process.env.DOMAIN || '',
      validate: (input) => {
        if (!input) return true
        if (!isValidDomain(input)) return 'Invalid domain format'
        return true
      },
    },
    {
      type: 'input',
      name: 'password',
      message: 'Code-Server password:',
      default: process.env.CODE_SERVER_PASSWORD || '',
      validate: (input) => {
        if (!input) return 'Required'
        if (input.length < 4) return 'Min 4 characters'
        return true
      },
    },
  ])

  // Projects directory — must be under vpsbot home so the vpsbot user can access it
  const projectsDir = '/home/vpsbot/projects'
  mkdirSync(projectsDir, { recursive: true })

  // Generate .env
  const envLines = [
    '# Auto-generated by VPS-CODE-BOT Setup',
    '',
    `BOT_TOKEN=${answers.botToken}`,
    `CHAT_ID=${answers.chatId}`,
    answers.domain ? `DOMAIN=${answers.domain}` : `IP_ADDRESS=${ipAddress}`,
    answers.domain ? '' : 'PORT=80',
    `PROJECTS_DIR=${projectsDir}`,
    `CLAUDE_CLI=${cliPath}`,
    `NODE_BIN=${process.env.NODE_BIN || '/usr/bin/node'}`,
    `CODE_SERVER_PASSWORD=${answers.password}`,
    'CODE_SERVER_PORT=8080',
    'CADDY_ADMIN_URL=http://localhost:2019',
    'DOCKER_SOCKET=/var/run/docker.sock',
    '',
  ].filter(l => l !== undefined).join('\n')

  writeFileSync(envFile, envLines)
  console.log(chalk.green('\n✓ Configuration saved\n'))
  console.log(`  IP:          ${ipAddress}`)
  console.log(`  Code-Server: http://${ipAddress}:8080`)
  console.log(`  Projects:    ${projectsDir}`)
  console.log(`  Domain:      ${answers.domain || chalk.gray('not set — using IP')}`)
  console.log(`  Telegram:    configured ✓\n`)
}

// Run if executed directly
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  runSetupWizard().catch(err => {
    console.error(chalk.red('Error:'), err.message)
    process.exit(1)
  })
}

export { runSetupWizard }
