#!/usr/bin/env node

import 'dotenv/config'
import { writeFileSync, existsSync, mkdirSync } from 'fs'
import { execSync } from 'child_process'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'
import inquirer from 'inquirer'
import chalk from 'chalk'

const __dirname = dirname(fileURLToPath(import.meta.url))
const projectRoot = dirname(__dirname)
const envFile = join(projectRoot, '.env')

// Helper functions
function isValidBotToken(token) {
  return /^\d+:[A-Za-z0-9_-]+$/.test(token)
}

function isValidChatId(id) {
  return /^-?\d+$/.test(id)
}

function isValidDomain(domain) {
  return /^([a-z0-9]([a-z0-9-]*[a-z0-9])?\.)*[a-z0-9]([a-z0-9-]*[a-z0-9])?$/.test(domain)
}

function isValidIp(ip) {
  const parts = ip.split('.')
  return parts.length === 4 && parts.every(p => {
    const num = parseInt(p)
    return num >= 0 && num <= 255
  })
}

function isValidPort(port) {
  const num = parseInt(port)
  return num > 0 && num < 65536
}

function detectIpAddress() {
  try {
    // Try to get the public/primary IP
    const result = execSync("hostname -I 2>/dev/null | awk '{print $1}' || curl -sf ifconfig.me 2>/dev/null || echo ''", { stdio: ['pipe', 'pipe', 'pipe'] })
    const ip = result.toString().trim()
    if (ip && isValidIp(ip)) return ip
  } catch {}
  return null
}

function detectClaudeCode(providedPath) {
  if (providedPath && existsSync(providedPath)) {
    return providedPath
  }

  // Try to find 'claude' command (npm global install)
  try {
    const which = execSync('which claude 2>/dev/null', { stdio: ['pipe', 'pipe', 'pipe'] })
    const p = which.toString().trim()
    if (p) return p
  } catch {}

  // Check various common locations
  const paths = [
    process.env.CLAUDE_CLI,
    '/usr/local/bin/claude',
    '/usr/local/bin/claude-code',
  ]

  for (const path of paths) {
    if (path && existsSync(path)) return path
  }

  return null
}

async function runSetupWizard() {
  console.log(chalk.cyan(`\n┌─────────────────────────────────────────────────────┐`))
  console.log(chalk.cyan(`│  VPS-CODE-BOT Setup                                  │`))
  console.log(chalk.cyan(`│  Configure your intelligent VPS platform             │`))
  console.log(chalk.cyan(`└─────────────────────────────────────────────────────┘\n`))

  // Check if already configured
  if (existsSync(envFile) && process.env.BOT_TOKEN && process.env.CHAT_ID) {
    const { reconfigure } = await inquirer.prompt([
      {
        type: 'confirm',
        name: 'reconfigure',
        message: 'System already configured. Reconfigure?',
        default: false,
      },
    ])

    if (!reconfigure) {
      console.log(chalk.gray('\nSetup skipped.\n'))
      return
    }
  }

  // Detect Claude Code (installed by install.sh or already present)
  const cliArg = process.argv.includes('--claude-cli')
    ? process.argv[process.argv.indexOf('--claude-cli') + 1]
    : null
  let cliPath = (cliArg && cliArg !== '' && cliArg !== '--os') ? cliArg : detectClaudeCode()

  if (cliPath) {
    console.log(chalk.green(`✓ Claude Code CLI: ${cliPath}\n`))
  } else {
    cliPath = 'claude'
    console.log(chalk.yellow('⚠ Claude Code CLI not found — install later: npm install -g @anthropic-ai/claude-code\n'))
  }

  // Auto-detect IP
  const ipAddress = detectIpAddress() || 'localhost'
  console.log(chalk.green(`✓ Server IP: ${ipAddress}\n`))

  // Code-Server password
  const codeServerConfig = await inquirer.prompt([{
    type: 'input',
    name: 'password',
    message: 'Code-Server password:',
    validate: (input) => {
      if (!input) return 'Password is required'
      if (input.length < 4) return 'Min 4 characters'
      return true
    },
  }])

  // Projects directory
  const projectsDir = `${process.env.HOME}/vps-code-bot-projects`
  mkdirSync(projectsDir, { recursive: true })

  // Read existing .env to preserve Telegram/Domain settings
  let existingDomain = process.env.DOMAIN || ''
  let existingBotToken = process.env.BOT_TOKEN || ''
  let existingChatId = process.env.CHAT_ID || ''

  // Generate .env file
  const envLines = [
    '# Generated by VPS-CODE-BOT Setup',
    '',
    '# Network',
    existingDomain ? `DOMAIN=${existingDomain}` : `IP_ADDRESS=${ipAddress}`,
    existingDomain ? '' : 'PORT=80',
    'CADDY_ADMIN_URL=http://localhost:2019',
    '',
    '# Storage',
    `PROJECTS_DIR=${projectsDir}`,
    '',
    '# Claude Code',
    `CLAUDE_CLI=${cliPath}`,
    `NODE_BIN=${process.env.NODE_BIN || '/usr/bin/node'}`,
    '',
    '# Code-Server',
    `CODE_SERVER_PASSWORD=${codeServerConfig.password}`,
    'CODE_SERVER_PORT=8080',
    '',
    '# Telegram (configure from CLI menu)',
    existingBotToken ? `BOT_TOKEN=${existingBotToken}` : '# BOT_TOKEN=',
    existingChatId ? `CHAT_ID=${existingChatId}` : '# CHAT_ID=',
    '',
    '# Docker',
    'DOCKER_SOCKET=/var/run/docker.sock',
    '',
  ].filter(l => l !== undefined).join('\n')

  writeFileSync(envFile, envLines)
  console.log(chalk.green('\n✓ Configuration saved\n'))
  console.log(`  IP:          ${ipAddress}`)
  console.log(`  Code-Server: http://${ipAddress}:8080`)
  console.log(`  Projects:    ${projectsDir}`)
  console.log(`  Domain:      ${existingDomain || chalk.gray('not set (configure from menu)')}`)
  console.log(`  Telegram:    ${existingBotToken ? 'configured' : chalk.gray('not set (configure from menu)')}\n`)
}

// Run if executed directly
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  runSetupWizard().catch(err => {
    console.error(chalk.red('Error:'), err.message)
    process.exit(1)
  })
}

export { runSetupWizard }
